# Generated by Django 4.2.9 on 2024-01-14 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_hashtag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_a', models.TextField(blank=True, verbose_name='내용')),
                ('content_b', models.TextField(blank=True, verbose_name='솔루션')),
                ('content_c', models.TextField(blank=True, verbose_name='느낀점')),
                ('created2', models.DateTimeField(auto_now_add=True, verbose_name='작성일시')),
                ('tags', models.ManyToManyField(blank=True, to='posts.hashtag', verbose_name='해시태그 목록3')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
        ),
    ]
