# Generated by Django 4.2.9 on 2024-01-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEntry_a',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, verbose_name='공지사항')),
            ],
        ),
        migrations.CreateModel(
            name='TextEntry_b',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(blank=True, verbose_name='성경말씀')),
            ],
        ),
    ]
