# Generated by Django 4.2.9 on 2024-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_textentry_a_textentry_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='post2',
            name='a_class_a',
            field=models.CharField(blank=True, help_text='내용분류', max_length=10, verbose_name='내용분류'),
        ),
        migrations.AddField(
            model_name='post2',
            name='consult_time',
            field=models.CharField(blank=True, help_text='ex: 20분:20', max_length=3, verbose_name='상담시간'),
        ),
        migrations.AddField(
            model_name='post2',
            name='content_d',
            field=models.TextField(blank=True, verbose_name='상담사례'),
        ),
        migrations.AddField(
            model_name='post2',
            name='education',
            field=models.CharField(blank=True, help_text='학력', max_length=10, verbose_name='학력'),
        ),
        migrations.AddField(
            model_name='post2',
            name='job',
            field=models.CharField(blank=True, help_text='직업', max_length=10, verbose_name='직업'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tag_condition_A',
            field=models.CharField(blank=True, choices=[('1', '성숙'), ('2', '미성숙'), ('3', '양호'), ('4', '기타')], help_text='신앙상태 성숙:1 미성숙:2 양호:3 기타:4', max_length=1, verbose_name='신앙상태'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tag_condition_B',
            field=models.CharField(blank=True, choices=[('1', '안정'), ('2', '불안정'), ('3', '양호'), ('4', '기타')], help_text='정서상태 안정:1 불안정:2 중간:3 기타:4', max_length=1, verbose_name='정서상태'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], help_text='남성: M 여성: F', max_length=1, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_marriage',
            field=models.CharField(blank=True, choices=[('1', '기혼'), ('2', '미혼'), ('3', '기타')], help_text='기혼:1 미혼:2 기타:3', max_length=1, verbose_name='결혼여부'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_phone',
            field=models.CharField(blank=True, help_text='숫자만 넣어주세요 : 0101231234', max_length=15, verbose_name='전화번호'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_position',
            field=models.CharField(blank=True, help_text='직분', max_length=10, verbose_name='직분'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_religion',
            field=models.CharField(blank=True, choices=[('1', '본교'), ('2', '타교'), ('3', '불신'), ('4', '기타')], help_text='본교:1 타교:2 불신:3 기타:4', max_length=1, verbose_name='종교'),
        ),
        migrations.AddField(
            model_name='post2',
            name='tags_years',
            field=models.CharField(blank=True, choices=[('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대'), ('6', '60대'), ('7', '70대')], help_text='숫자만 넣어주세요 ex 20대:2', max_length=1, verbose_name='연령'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='content_a',
            field=models.TextField(blank=True, verbose_name='호소한내용'),
        ),
    ]
