# Generated by Django 4.2.9 on 2024-01-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post2_a_class_a_post2_consult_time_post2_content_d_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='tag_condition_A',
            field=models.CharField(blank=True, choices=[('0', 'PASS'), ('1', '성숙'), ('2', '미성숙'), ('3', '양호'), ('4', '기타')], help_text='신앙상태 성숙:1 미성숙:2 양호:3 기타:4', max_length=1, verbose_name='신앙상태'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tag_condition_B',
            field=models.CharField(blank=True, choices=[('0', 'PASS'), ('1', '안정'), ('2', '불안정'), ('3', '양호'), ('4', '기타')], help_text='정서상태 안정:1 불안정:2 중간:3 기타:4', max_length=1, verbose_name='정서상태'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tags_marriage',
            field=models.CharField(blank=True, choices=[('0', 'PASS'), ('1', '기혼'), ('2', '미혼'), ('3', '기타')], help_text='기혼:1 미혼:2 기타:3', max_length=1, verbose_name='결혼여부'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tags_religion',
            field=models.CharField(blank=True, choices=[('0', 'PASS'), ('1', '본교'), ('2', '타교'), ('3', '불신'), ('4', '기타')], help_text='본교:1 타교:2 불신:3 기타:4', max_length=1, verbose_name='종교'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tags_years',
            field=models.CharField(blank=True, choices=[('0', '모름'), ('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대'), ('6', '60대'), ('7', '70대')], help_text='숫자만 넣어주세요 ex 20대:2', max_length=1, verbose_name='연령'),
        ),
    ]
