# Generated by Django 4.2.9 on 2024-01-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post2_tag_condition_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='tags_gender',
            field=models.CharField(blank=True, choices=[('M', '남성'), ('F', '여성')], max_length=1, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tags_marriage',
            field=models.CharField(blank=True, choices=[('0', 'PASS'), ('1', '기혼'), ('2', '미혼'), ('3', '기타')], max_length=1, verbose_name='결혼여부'),
        ),
        migrations.AlterField(
            model_name='post2',
            name='tags_years',
            field=models.CharField(blank=True, choices=[('0', '모름'), ('1', '10대'), ('2', '20대'), ('3', '30대'), ('4', '40대'), ('5', '50대'), ('6', '60대'), ('7', '70대')], max_length=1, verbose_name='연령'),
        ),
    ]
