# Generated by Django 4.2.9 on 2024-01-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment2'),
        ('users', '0004_relationship_user_following_relationship_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='like_posts',
            field=models.ManyToManyField(blank=True, related_name='like_users', to='posts.post2', verbose_name='좋아요 누른 Post목록'),
        ),
    ]
