# Generated by Django 4.2.9 on 2024-01-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_like_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='이름'),
        ),
    ]
