# Generated by Django 4.2.9 on 2024-01-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='korean_name',
            field=models.TextField(blank=True, verbose_name='이름'),
        ),
    ]
