# Generated by Django 4.2.9 on 2024-01-15 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_korean_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='korean_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='short_description',
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
